// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC22SMWAvEJk0IJcQOhdthqTfZUbqpPNGg',
    appId: '1:25488214859:web:f1adc721254d3a868a36ce',
    messagingSenderId: '25488214859',
    projectId: 'accountauthsystem',
    authDomain: 'accountauthsystem.firebaseapp.com',
    storageBucket: 'accountauthsystem.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaHH8zAzILav15SC5Mx9O1aia3vkjTocM',
    appId: '1:25488214859:android:348032f70d5f525d8a36ce',
    messagingSenderId: '25488214859',
    projectId: 'accountauthsystem',
    storageBucket: 'accountauthsystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxvR2OMtYsJXDJSTiE6IbdIEJt-qdjyi8',
    appId: '1:25488214859:ios:1d689a5591c4e93b8a36ce',
    messagingSenderId: '25488214859',
    projectId: 'accountauthsystem',
    storageBucket: 'accountauthsystem.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxvR2OMtYsJXDJSTiE6IbdIEJt-qdjyi8',
    appId: '1:25488214859:ios:1d689a5591c4e93b8a36ce',
    messagingSenderId: '25488214859',
    projectId: 'accountauthsystem',
    storageBucket: 'accountauthsystem.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC22SMWAvEJk0IJcQOhdthqTfZUbqpPNGg',
    appId: '1:25488214859:web:d593643429742b838a36ce',
    messagingSenderId: '25488214859',
    projectId: 'accountauthsystem',
    authDomain: 'accountauthsystem.firebaseapp.com',
    storageBucket: 'accountauthsystem.appspot.com',
  );
}
